import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, radius, useThemeMode } from '../theme';

export function useViewGradesStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  content: {
    flex: 1,
  },
  loading: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    lineHeight: 38,
    fontFamily: F.outfitBlack,
    color: ink.ink,
    letterSpacing: -0.8,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  filterPanel: {
    marginBottom: 16,
    padding: 16,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: ink.canvas,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 12,
    marginBottom: 14,
    backgroundColor: ink.canvas,
  },
  searchRowIconWrap: {
    justifyContent: 'center',
    marginRight: 4,
  },
  searchInputInner: {
    flex: 1,
    paddingHorizontal: 8,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
    ...Platform.select({
      ios: {
        paddingVertical: 12,
      },
      android: {
        paddingVertical: 10,
        textAlignVertical: 'center',
      },
      default: {
        paddingVertical: 12,
      },
    }),
  },
  searchClear: {
    padding: 4,
  },
  filterPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 12,
  },
  filtersHeaderLead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  filterHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  collapseFiltersBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  collapseFiltersBtnTxt: {
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
  },
  filterCollapsedHint: {
    marginBottom: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: radius.input,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: theme.primarySoft,
  },
  filterCollapsedHintLabel: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  filterCollapsedHintValue: {
    fontSize: 15,
    fontFamily: F.dmMedium,
    color: ink.ink,
    marginBottom: 6,
  },
  filterCollapsedTap: {
    fontSize: 12,
    fontFamily: F.dmRegular,
    color: theme.primary,
  },
  filterPanelTitle: {
    fontSize: 15,
    fontFamily: F.outfitBold,
    color: ink.ink,
    letterSpacing: -0.2,
  },
  resetBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  resetBtnPressed: {
    opacity: 0.85,
  },
  resetBtnDisabled: {
    opacity: 0.45,
  },
  resetBtnTxt: {
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  resetBtnTxtDisabled: {
    color: ink.inkSoft,
  },
  filterLabel: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginTop: 4,
  },
  chipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 8,
    paddingBottom: 4,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    maxWidth: 280,
  },
  chipOn: {
    backgroundColor: theme.primarySoft,
    borderColor: theme.primary,
  },
  chipTxt: {
    fontSize: 13,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
  },
  chipTxtOn: {
    color: theme.primary,
  },
  taskPickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: radius.input,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: 'rgba(160, 96, 255, 0.06)',
  },
  taskPickerBtnText: {
    flex: 1,
    fontSize: 15,
    fontFamily: F.dmMedium,
    color: ink.ink,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalDimmer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalSheetOuter: {
    maxHeight: '88%',
    width: '100%',
  },
  modalSheet: {
    backgroundColor: ink.canvas,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 28 : 16,
    paddingTop: 8,
    borderWidth: 1,
    borderColor: '#000000',
    borderBottomWidth: 0,
  },
  modalGrabber: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#CBD5E1',
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 12,
    textAlign: 'center',
  },
  modalSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  modalSearchInput: {
    flex: 1,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    paddingHorizontal: 8,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
  },
  modalList: {
    maxHeight: 420,
  },
  modalRow: {
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  modalRowOn: {
    backgroundColor: theme.primarySoft,
    marginHorizontal: -4,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderBottomWidth: 0,
  },
  modalRowTitle: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 4,
  },
  modalRowSub: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  modalEmpty: {
    textAlign: 'center',
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    paddingVertical: 24,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 100,
  },
  emptyCard: {
    padding: 24,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyBody: {
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    textAlign: 'center',
    lineHeight: 22,
  },
  classBlock: {
    marginBottom: 20,
    padding: 18,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  taskHeadRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  taskHeadPressable: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
    marginHorizontal: -4,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 10,
  },
  taskReportAffordance: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingTop: 2,
    marginLeft: 6,
  },
  taskReportLabel: {
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  classIconWell: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  taskHeadText: {
    flex: 1,
    minWidth: 0,
  },
  taskTitle: {
    fontSize: 17,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  taskMeta: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    lineHeight: 18,
  },
  rosterEmpty: {
    paddingVertical: 8,
  },
  rosterEmptyText: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  table: {
    borderRadius: 12,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    overflow: 'hidden',
  },
  tableHead: {
    flexDirection: 'row',
    backgroundColor: 'rgba(160, 96, 255, 0.08)',
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  th: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  thStudent: {
    flex: 1,
    minWidth: 0,
  },
  thStatus: {
    width: 76,
    textAlign: 'center',
  },
  thGrade: {
    width: 64,
    textAlign: 'right',
  },
  tr: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: ink.canvas,
  },
  trDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  tdStudent: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  tdStatus: {
    width: 76,
    alignItems: 'center',
  },
  statusTxt: {
    fontSize: 12,
    fontFamily: F.dmSemi,
  },
  studentName: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  studentEmail: {
    fontSize: 11,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginTop: 2,
  },
  tdGrade: {
    width: 64,
    alignItems: 'flex-end',
  },
  gradeBadge: {
    fontSize: 15,
    fontFamily: F.outfitBold,
    textAlign: 'right',
  },
  bottomSpacer: {
    height: 24,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
