import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, radius, useThemeMode } from '../theme';

export function useAttendanceStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
    backgroundColor: ink.canvas,
  },
  headerText: {
    flex: 1,
    paddingLeft: 4,
    minWidth: 0,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontFamily: F.outfitBlack,
    color: ink.ink,
    letterSpacing: -0.6,
    marginBottom: 4,
  },
  subDate: {
    fontSize: 14,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
    marginBottom: 2,
  },
  subClass: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  subMeta: {
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    fontWeight: '400',
  },
  summaryCard: {
    marginHorizontal: 20,
    marginTop: 16,
    padding: 16,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  summaryEyebrow: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryCell: {
    flexGrow: 1,
    minWidth: '22%',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  summaryCellMuted: {
    backgroundColor: 'rgba(26, 26, 34, 0.06)',
  },
  summaryNum: {
    fontSize: 22,
    lineHeight: 26,
    fontFamily: F.outfitBold,
    marginBottom: 2,
  },
  summaryLab: {
    fontSize: 11,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
  },
  searchWrap: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchInput: {
    backgroundColor: ink.canvas,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
  },
  scroll: {
    flex: 1,
  },
  /** Single scroll for header → summary → search → roster */
  scrollPageContent: {
    flexGrow: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  rosterEmpty: {
    paddingVertical: 28,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  rosterEmptyTitle: {
    fontSize: 17,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 8,
    textAlign: 'center',
  },
  rosterEmptyBody: {
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  listEyebrow: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  studentCard: {
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.card,
    padding: 14,
    marginBottom: 10,
    backgroundColor: ink.canvas,
  },
  studentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.primarySoft,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarLetter: {
    fontSize: 16,
    fontFamily: F.dmBold,
    color: theme.primary,
  },
  studentName: {
    flex: 1,
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  segment: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: 12,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    overflow: 'hidden',
    backgroundColor: 'rgba(26, 26, 34, 0.03)',
  },
  segBtn: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 4,
  },
  segLeft: {},
  segRight: {},
  segDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: ink.rowDivider,
  },
  segLabel: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
  },
  segLabelOnLight: {
    color: theme.white,
  },
  segActivePresent: {
    backgroundColor: '#0D9488',
  },
  segActiveLate: {
    backgroundColor: '#D97706',
  },
  segActiveAbsent: {
    backgroundColor: '#DC2626',
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: ink.rowDivider,
    backgroundColor: ink.canvas,
  },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: radius.btn,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnPressed: {
    opacity: 0.92,
  },
  saveBtnDisabled: {
    opacity: 0.45,
  },
  saveBtnText: {
    fontSize: 17,
    fontFamily: F.outfitBold,
    color: theme.white,
  },
  pickSub: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginTop: 4,
  },
  pickScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  pickEmpty: {
    paddingVertical: 32,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  pickEmptyTitle: {
    fontSize: 20,
    fontFamily: F.outfitExtraBold,
    color: ink.ink,
    marginBottom: 8,
    textAlign: 'center',
  },
  pickEmptyBody: {
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
    maxWidth: 300,
  },
  pickPrimaryBtn: {
    backgroundColor: theme.primary,
    borderRadius: radius.btn,
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  pickPrimaryBtnText: {
    fontSize: 16,
    fontFamily: F.outfitBold,
    color: theme.white,
  },
  pickCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.card,
    padding: 14,
    marginBottom: 10,
    backgroundColor: ink.canvas,
  },
  pickCardPressed: {
    opacity: 0.92,
  },
  pickIconWell: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: theme.primarySoft,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  pickCardMain: {
    flex: 1,
    minWidth: 0,
  },
  pickCardTitle: {
    fontSize: 17,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 4,
  },
  pickCardMeta: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    lineHeight: 20,
  },
  pickCardSchedule: {
    fontSize: 12,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginTop: 4,
  },
  pickChevron: {
    fontSize: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginLeft: 4,
  },
  changeClassLink: {
    marginTop: 8,
    fontSize: 14,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  headerAddBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    marginLeft: 8,
    marginTop: 2,
  },
  headerAddBtnPressed: {
    opacity: 0.9,
  },
  addWideWrap: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  addWideBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: radius.card,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  addWideBtnTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: theme.white,
  },
  modalRoot: {
    flex: 1,
  },
  modalDimmer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalCenter: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 6,
  },
  modalHint: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  modalInput: {
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 16,
    fontFamily: F.dmRegular,
    color: ink.ink,
    marginBottom: 14,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 4,
  },
  modalCancel: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  modalCancelTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  modalSave: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  modalSaveTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: theme.white,
  },
  menuCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 18,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  menuTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 6,
  },
  menuHint: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 14,
  },
  menuOption: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: radius.input,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    marginBottom: 10,
  },
  menuOptionPressed: {
    opacity: 0.92,
  },
  menuOptionTitle: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 4,
  },
  menuOptionSub: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    lineHeight: 18,
  },
  menuDismiss: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 4,
  },
  menuDismissTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  csvCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    maxHeight: '88%',
  },
  csvDetailHeading: {
    fontSize: 15,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginTop: 4,
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  csvDetailBody: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 14,
  },
  csvHelpLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  csvHelp: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 12,
  },
  csvMono: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 13,
    color: ink.ink,
  },
  csvTextarea: {
    minHeight: 160,
    maxHeight: 280,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.ink,
    marginBottom: 16,
    backgroundColor: ink.canvas,
  },
  csvActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    flexWrap: 'wrap',
  },
  csvConfirm: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
