import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, radius, useThemeMode } from '../theme';

export function useCreateClassStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingLeft: 8,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
    backgroundColor: ink.canvas,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    flex: 1,
    marginLeft: 2,
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    letterSpacing: -0.3,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 48,
  },
  section: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 8,
  },
  sectionFirst: {
    paddingTop: 20,
  },
  sectionEyebrow: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 14,
  },
  sectionLead: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 18,
    maxWidth: 400,
  },
  field: {
    marginBottom: 22,
  },
  label: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 10,
  },
  labelSpaced: {
    marginTop: 8,
  },
  input: {
    backgroundColor: ink.canvas,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
  },
  gradeScrollContent: {
    paddingVertical: 4,
    gap: 10,
    paddingRight: 8,
  },
  gradeChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    marginRight: 8,
  },
  gradeChipOn: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  gradeChipTxt: {
    fontSize: 14,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
  },
  gradeChipTxtOn: {
    color: theme.white,
  },
  dayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 4,
  },
  dayChip: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radius.btn,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    minWidth: 52,
    alignItems: 'center',
  },
  dayChipOn: {
    backgroundColor: theme.primarySoft,
    borderColor: theme.primary,
  },
  dayChipTxt: {
    fontSize: 14,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
  },
  dayChipTxtOn: {
    color: theme.primary,
  },
  timeTrigger: {
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.card,
    paddingVertical: 18,
    paddingHorizontal: 18,
    backgroundColor: ink.canvas,
  },
  timeTriggerLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  timeTriggerValue: {
    fontSize: 28,
    fontFamily: F.outfitBold,
    color: ink.ink,
    letterSpacing: -0.5,
  },
  timeTriggerHint: {
    marginTop: 8,
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  scheduleBlock: {
    marginBottom: 22,
  },
  scheduleBlockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  scheduleBlockTitle: {
    fontSize: 15,
    fontFamily: F.dmBold,
    color: ink.ink,
  },
  scheduleBlockRemove: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: '#DC2626',
  },
  addMeetingBtn: {
    alignSelf: 'flex-start',
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop: 4,
    marginBottom: 8,
  },
  addMeetingBtnTxt: {
    fontSize: 16,
    fontFamily: F.dmBold,
    color: theme.primary,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  timeSheet: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: ink.canvas,
    borderRadius: radius.card + 4,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
    paddingBottom: 16,
  },
  timeSheetTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 12,
    textAlign: 'center',
  },
  iosPicker: {
    height: 180,
  },
  timeSheetDone: {
    marginTop: 8,
    backgroundColor: theme.primary,
    borderRadius: radius.btn,
    paddingVertical: 14,
    alignItems: 'center',
  },
  timeSheetDoneTxt: {
    fontSize: 17,
    fontFamily: F.outfitBold,
    color: theme.white,
  },
  studentsSection: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
  },
  studentActions: {
    marginBottom: 18,
  },
  csvBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: radius.btn,
    borderWidth: ink.borderWidth,
    borderColor: theme.primary,
    backgroundColor: theme.primarySoft,
  },
  csvBtnTxt: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  subLabel: {
    fontSize: 14,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 10,
  },
  addRow: {
    gap: 12,
    marginBottom: 8,
  },
  addInput: {
    marginBottom: 0,
  },
  addInputNarrow: {
    marginBottom: 0,
    maxWidth: 140,
    alignSelf: 'stretch',
  },
  addCircle: {
    alignSelf: 'flex-end',
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  roster: {
    marginTop: 22,
    paddingTop: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: ink.rowDivider,
  },
  rosterTitle: {
    fontSize: 15,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 14,
  },
  studentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    marginBottom: 10,
    backgroundColor: ink.canvas,
  },
  studentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  studentTxt: {
    flex: 1,
    minWidth: 0,
  },
  studentName: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  studentEmail: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginTop: 2,
  },
  createBtn: {
    marginHorizontal: 24,
    marginTop: 28,
    backgroundColor: theme.primary,
    borderRadius: radius.btn,
    paddingVertical: 16,
    alignItems: 'center',
  },
  createBtnTxt: {
    fontSize: 17,
    fontFamily: F.outfitBold,
    color: theme.white,
  },
  bottomPad: {
    height: 32,
  },
  csvSheet: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: ink.canvas,
    borderRadius: radius.card + 4,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
  },
  csvSheetTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 8,
  },
  csvBulkHeading: {
    fontSize: 15,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  csvBulkBody: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 12,
  },
  csvFormatLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  csvSheetHelp: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 14,
  },
  csvMono: {
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  csvTextarea: {
    minHeight: 140,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    padding: 14,
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.ink,
    marginBottom: 18,
  },
  csvActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  csvCancel: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  csvCancelTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
  },
  csvConfirm: {
    backgroundColor: theme.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: radius.btn,
  },
  csvConfirmTxt: {
    fontSize: 16,
    fontFamily: F.outfitBold,
    color: theme.white,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
