import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, useThemeMode } from '../theme';

export function useClassDetailsStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: ink.rowDivider,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Outfit-Bold',
    color: ink.ink,
  },
  placeholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  infoCard: {
    backgroundColor: '#F8F5FF',
    borderWidth: 1,
    borderColor: '#E0D5FF',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 24,
    marginTop: 20,
    marginBottom: 20,
  },
  className: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'Outfit-Bold',
    color: ink.ink,
    marginBottom: 8,
  },
  schoolLine: {
    fontSize: 14,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
    marginBottom: 10,
  },
  classSubject: {
    fontSize: 16,
    fontFamily: 'DMSans-Regular',
    color: '#1A1A22',
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'DMSans-Regular',
    color: '#1A1A22',
    marginRight: 8,
  },
  roomText: {
    fontSize: 14,
    fontFamily: 'DMSans-Regular',
    color: '#1A1A22',
  },
  quickActionsSection: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Outfit-Bold',
    color: ink.ink,
    marginBottom: 16,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  quickActionCard: {
    width: '47%',
    backgroundColor: ink.canvas,
    borderWidth: 1,
    borderColor: ink.borderInk,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  quickActionIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  quickActionTitle: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'DMSans-SemiBold',
    color: ink.ink,
    textAlign: 'center',
  },
  sectionOuter: {
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  borderedSection: {
    backgroundColor: ink.canvas,
    borderWidth: 1,
    borderColor: ink.borderInk,
    borderRadius: 12,
    padding: 16,
  },
  sectionTitleInCard: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Outfit-Bold',
    color: ink.ink,
    marginBottom: 8,
  },
  announcementLead: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
    marginBottom: 14,
  },
  announcementComposer: {
    marginBottom: 16,
  },
  announcementInput: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: ink.rowDivider,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 15,
    fontFamily: 'DMSans-Regular',
    color: '#1A1A22',
    backgroundColor: '#FAFAFA',
    marginBottom: 12,
  },
  postAnnouncementBtn: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  postAnnouncementBtnPressed: {
    opacity: 0.9,
  },
  postAnnouncementBtnText: {
    fontSize: 16,
    fontFamily: 'DMSans-SemiBold',
    color: theme.white,
  },
  announcementList: {
    marginTop: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: ink.rowDivider,
  },
  announcementRow: {
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  announcementRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  announcementRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  announcementDate: {
    fontSize: 12,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
  },
  announcementBody: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'DMSans-Regular',
    color: '#1A1A22',
  },
  announcementEmpty: {
    fontSize: 14,
    fontFamily: 'DMSans-Regular',
    color: ink.placeholder,
    fontStyle: 'italic',
    marginTop: 4,
  },
  activitySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  notifPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: ink.borderInk,
    backgroundColor: 'rgba(160, 96, 255, 0.08)',
  },
  notifPillText: {
    fontSize: 11,
    fontFamily: 'DMSans-SemiBold',
    color: ink.ink,
    letterSpacing: 0.2,
  },
  activityIntro: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
    marginBottom: 12,
  },
  activityEmptyBox: {
    paddingVertical: 12,
  },
  activityEmptyTitle: {
    fontSize: 15,
    fontFamily: 'DMSans-SemiBold',
    color: '#1A1A22',
    marginBottom: 4,
  },
  activityEmptySub: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
  },
  activityList: {
    gap: 0,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  activityUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.primary,
    marginTop: 14,
    marginRight: 8,
  },
  activityIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(160, 96, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  activityCopy: {
    flex: 1,
    minWidth: 0,
  },
  activityHeadline: {
    fontSize: 15,
    fontFamily: 'DMSans-SemiBold',
    color: ink.ink,
    marginBottom: 4,
  },
  activityDetail: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'DMSans-Regular',
    color: '#475569',
    marginBottom: 6,
  },
  activityTime: {
    fontSize: 12,
    fontFamily: 'DMSans-Regular',
    color: ink.placeholder,
  },
  deleteBtn: {
    marginHorizontal: 24,
    marginTop: 8,
    marginBottom: 32,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(220, 38, 38, 0.45)',
    backgroundColor: 'rgba(220, 38, 38, 0.06)',
    alignItems: 'center',
  },
  deleteBtnText: {
    fontSize: 16,
    fontFamily: 'DMSans-SemiBold',
    color: '#DC2626',
  },
  notFoundWrap: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notFoundTitle: {
    fontSize: 20,
    fontFamily: 'Outfit-Bold',
    color: ink.ink,
    marginBottom: 8,
  },
  notFoundSub: {
    fontSize: 15,
    fontFamily: 'DMSans-Regular',
    color: '#64748B',
    marginBottom: 20,
    textAlign: 'center',
  },
  notFoundBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.primary,
  },
  notFoundBtnTxt: {
    fontSize: 16,
    fontFamily: 'DMSans-SemiBold',
    color: theme.white,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
