import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, radius, useThemeMode } from '../theme';

export function useQuizzesStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontFamily: F.outfitBlack,
    color: ink.ink,
    letterSpacing: -0.75,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 112,
  },
  topBand: {
    backgroundColor: ink.canvas,
    paddingTop: 8,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  statsCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    paddingVertical: 14,
    paddingHorizontal: 4,
    marginBottom: 14,
  },
  statCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statRule: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: ink.rowDivider,
    marginVertical: 4,
  },
  statNum: {
    fontSize: 22,
    lineHeight: 26,
    fontFamily: F.dmExtraBold,
    color: ink.ink,
    letterSpacing: -0.4,
  },
  statLab: {
    marginTop: 4,
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 0.3,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: ink.canvas,
  },
  searchInput: {
    flex: 1,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    paddingHorizontal: 10,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
  },
  chipsScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 14,
    paddingRight: 8,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  chipOn: {
    backgroundColor: ink.ink,
    borderColor: ink.ink,
  },
  chipTxt: {
    fontSize: 14,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
  },
  chipTxtOn: {
    color: ink.canvas,
  },
  createCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primary,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  createCardPressed: {
    opacity: 0.94,
  },
  createIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  createCopy: {
    flex: 1,
    minWidth: 0,
  },
  createTitle: {
    fontSize: 17,
    lineHeight: 22,
    fontFamily: F.outfitBold,
    color: theme.white,
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  createSub: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.dmRegular,
    color: 'rgba(255,255,255,0.88)',
  },
  sectionLabel: {
    marginTop: 22,
    marginBottom: 12,
    paddingHorizontal: 20,
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  listBlock: {
    paddingHorizontal: 20,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 14,
  },
  itemCardMargin: {
    marginBottom: 12,
  },
  itemCardPressed: {
    opacity: 0.97,
  },
  itemIconColumn: {
    alignItems: 'center',
    marginRight: 12,
    gap: 8,
  },
  itemIconWell: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemMain: {
    flex: 1,
    minWidth: 0,
  },
  itemTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  itemTitle: {
    flex: 1,
    fontSize: 17,
    lineHeight: 22,
    fontFamily: F.dmBold,
    color: ink.ink,
  },
  kindPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  kindPillTxt: {
    fontSize: 11,
    fontFamily: F.dmBold,
    letterSpacing: 0.2,
  },
  itemClass: {
    fontSize: 14,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
    marginBottom: 6,
  },
  itemMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemMeta: {
    fontSize: 12,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  itemMetaDot: {
    fontSize: 12,
    color: ink.inkSoft,
    marginHorizontal: 6,
  },
  progressTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: ink.rowDivider,
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  progressLab: {
    fontSize: 11,
    fontFamily: F.dmMedium,
    color: ink.inkSoft,
  },
  itemSide: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginLeft: 8,
    gap: 6,
  },
  sideActionsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
  },
  itemSideChevron: {
    marginTop: 6,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnPressed: {
    opacity: 0.88,
  },
  iconBtnDisabled: {
    opacity: 0.45,
  },
  iconBtnDanger: {
    borderColor: 'rgba(220, 38, 38, 0.42)',
  },
  emptyCard: {
    marginHorizontal: 20,
    alignItems: 'center',
    paddingVertical: 36,
    paddingHorizontal: 24,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderStyle: 'dashed',
    backgroundColor: ink.canvas,
  },
  emptyIconWell: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: ink.iconWell,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyBody: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    textAlign: 'center',
    marginBottom: 18,
  },
  emptyCta: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 12,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: '#000000',
  },
  emptyCtaTxt: {
    fontSize: 16,
    fontFamily: F.outfitBold,
    color: theme.white,
  },
  bottomPad: {
    height: 8,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
