import { useMemo } from 'react';
import { StyleSheet, Platform } from 'react-native';
import { fonts as F, radius, useThemeMode } from '../theme';

export function useViewStudentsStyles() {
  const { ink, theme } = useThemeMode();
  const styles = useMemo(
    () =>
      StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ink.canvas,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingLeft: 8,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
    backgroundColor: ink.canvas,
  },
  headerTitle: {
    flex: 1,
    marginLeft: 2,
    fontSize: 22,
    fontFamily: F.outfitBold,
    color: ink.ink,
    letterSpacing: -0.4,
  },
  headerSpacer: {
    width: 44,
  },
  headerAddBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  headerAddBtnPressed: {
    opacity: 0.9,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  heroCard: {
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.card,
    padding: 16,
    marginBottom: 14,
    backgroundColor: ink.canvas,
  },
  className: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  heroMeta: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  toolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  toolBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: ink.borderWidth,
  },
  toolBtnOutline: {
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  toolBtnDanger: {
    borderColor: 'rgba(220, 38, 38, 0.45)',
    backgroundColor: 'rgba(220, 38, 38, 0.06)',
  },
  toolBtnDisabled: {
    opacity: 0.45,
  },
  toolBtnPressed: {
    opacity: 0.88,
  },
  toolBtnTxt: {
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  toolBtnTxtDanger: {
    fontSize: 13,
    fontFamily: F.dmSemi,
    color: '#DC2626',
  },
  toolBtnTxtDisabled: {
    color: ink.inkSoft,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: ink.canvas,
  },
  searchInput: {
    flex: 1,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    paddingHorizontal: 8,
    fontSize: 15,
    fontFamily: F.dmRegular,
    color: ink.ink,
  },
  addWideBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: radius.card,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    marginBottom: 16,
  },
  addWideBtnTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: '#FFFFFF',
  },
  assignEveryoneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: radius.card,
    backgroundColor: ink.canvas,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    marginBottom: 16,
  },
  assignEveryoneBtnPressed: {
    opacity: 0.92,
  },
  assignEveryoneBtnDisabled: {
    opacity: 0.45,
  },
  assignEveryoneBtnTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  emptyCard: {
    padding: 18,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  emptyTitle: {
    fontSize: 17,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 8,
  },
  emptyBody: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
  },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  listCard: {
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    overflow: 'hidden',
    backgroundColor: ink.canvas,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: ink.canvas,
  },
  rowDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: ink.rowDivider,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ink.canvas,
  },
  checkboxOn: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  rowText: {
    flex: 1,
    minWidth: 0,
  },
  name: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  email: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginTop: 4,
  },
  emailMuted: {
    fontSize: 12,
    fontFamily: F.dmRegular,
    color: '#94A3B8',
    marginTop: 4,
    fontStyle: 'italic',
  },
  rowMainPress: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  rowChevron: {
    fontSize: 22,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginLeft: 4,
    paddingLeft: 4,
  },
  modalRoot: {
    flex: 1,
  },
  modalDimmer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalCenter: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
  },
  assignModalCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    maxHeight: '88%',
  },
  assignScroll: {
    flexGrow: 0,
  },
  assignSectionLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  assignHint: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    lineHeight: 20,
    marginBottom: 14,
  },
  orderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  orderChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
  },
  orderChipOn: {
    borderColor: theme.primary,
    backgroundColor: theme.primarySoft,
  },
  orderChipTxt: {
    fontSize: 14,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  assignPreview: {
    marginBottom: 14,
    padding: 12,
    borderRadius: radius.input,
    backgroundColor: theme.primarySoft,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  assignPreviewLabel: {
    fontSize: 11,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  assignPreviewTxt: {
    fontSize: 15,
    fontFamily: F.dmMedium,
    color: ink.ink,
    lineHeight: 22,
  },
  assignPreviewMuted: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    fontStyle: 'italic',
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 6,
  },
  modalHint: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  modalInput: {
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 16,
    fontFamily: F.dmRegular,
    color: ink.ink,
    marginBottom: 14,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 4,
  },
  modalCancel: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  modalCancelTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
  },
  modalSave: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },
  modalSaveTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: '#FFFFFF',
  },
  menuCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 18,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  menuTitle: {
    fontSize: 20,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginBottom: 6,
  },
  menuHint: {
    fontSize: 14,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 14,
  },
  menuOption: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: radius.input,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    backgroundColor: ink.canvas,
    marginBottom: 10,
  },
  menuOptionPressed: {
    opacity: 0.92,
  },
  menuOptionTitle: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: ink.ink,
    marginBottom: 4,
  },
  menuOptionSub: {
    fontSize: 13,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    lineHeight: 18,
  },
  menuDismiss: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 4,
  },
  menuDismissTxt: {
    fontSize: 16,
    fontFamily: F.dmSemi,
    color: theme.primary,
  },
  csvCard: {
    backgroundColor: ink.canvas,
    borderRadius: radius.card,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    padding: 20,
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    maxHeight: '88%',
  },
  csvDetailHeading: {
    fontSize: 15,
    fontFamily: F.outfitBold,
    color: ink.ink,
    marginTop: 4,
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  csvDetailBody: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 14,
  },
  csvHelpLabel: {
    fontSize: 12,
    fontFamily: F.dmSemi,
    color: ink.inkSoft,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  csvHelp: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.dmRegular,
    color: ink.inkSoft,
    marginBottom: 12,
  },
  csvMono: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 13,
    color: ink.ink,
  },
  csvTextarea: {
    minHeight: 160,
    maxHeight: 280,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
    borderRadius: radius.input,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: F.dmRegular,
    color: ink.ink,
    marginBottom: 16,
    backgroundColor: ink.canvas,
  },
  csvActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    flexWrap: 'wrap',
  },
  csvConfirm: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
    backgroundColor: theme.primary,
    borderWidth: ink.borderWidth,
    borderColor: ink.borderInk,
  },

      }),
    [ink, theme],
  );
  return { styles, ink, theme };
}
